name: Deploy to Azure Storage Static Website

on:
  push:
    branches: [master]
    paths-ignore: ["README.md"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Azure Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            # Clear existing files in container (optional - comment out if you want to keep old files)
            echo "Clearing existing files from \$web container..."
            az storage blob delete-batch \
              --account-name dfou28nflscoreboard \
              --source '$web' || echo "No existing files to delete"

            # Upload all built files from dist directory
            echo "Uploading files from ./dist to \$web container..."
            az storage blob upload-batch \
              --account-name dfou28nflscoreboard \
              --destination '$web' \
              --source './dist' \
              --overwrite

            # Copy staticwebapp.config.json to root (if it exists)
            if [ -f "staticwebapp.config.json" ]; then
              echo "Uploading staticwebapp.config.json..."
              az storage blob upload \
                --account-name dfou28nflscoreboard \
                --container-name '$web' \
                --file staticwebapp.config.json \
                --name staticwebapp.config.json \
                --content-type 'application/json' \
                --overwrite
            fi

      - name: Purge CDN (if applicable)
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Deployment completed successfully!"
            echo "Your site should be updated at your static website URL"
